// Code generated by generate-wrap; DO NOT EDIT.
package contextaware

import (
	"io"
)

func wrapIO(i interface{}) interface{} {
	type (
		t00i = io.Closer
		t01i = io.Reader
		t01o = Reader
		t02i = io.ReaderAt
		t02o = ReaderAt
		t03i = io.ReaderFrom
		t04i = io.Seeker
		t05i = io.Writer
		t05o = Writer
		t06i = io.WriterAt
		t06o = WriterAt
		t07i = io.WriterTo
	)

	var (
		f01 = wrapReader
		f02 = wrapReaderAt
		f05 = wrapWriter
		f06 = wrapWriterAt
	)

	var f uint64
	o00, b00 := i.(t00i)
	if b00 { f |= 0x0001 }
	o01, b01 := i.(t01i)
	if b01 { f |= 0x0002 }
	o02, b02 := i.(t02i)
	if b02 { f |= 0x0004 }
	o03, b03 := i.(t03i)
	if b03 { f |= 0x0008 }
	o04, b04 := i.(t04i)
	if b04 { f |= 0x0010 }
	o05, b05 := i.(t05i)
	if b05 { f |= 0x0020 }
	o06, b06 := i.(t06i)
	if b06 { f |= 0x0040 }
	o07, b07 := i.(t07i)
	if b07 { f |= 0x0080 }

	switch f {
	case 0x0000: return struct{}{}
	case 0x0001: return struct{t00i}{o00}
	case 0x0002: return struct{t01o}{f01(o01)}
	case 0x0003: return struct{t00i;t01o}{o00,f01(o01)}
	case 0x0004: return struct{t02o}{f02(o02)}
	case 0x0005: return struct{t00i;t02o}{o00,f02(o02)}
	case 0x0006: return struct{t01o;t02o}{f01(o01),f02(o02)}
	case 0x0007: return struct{t00i;t01o;t02o}{o00,f01(o01),f02(o02)}
	case 0x0008: return struct{t03i}{o03}
	case 0x0009: return struct{t00i;t03i}{o00,o03}
	case 0x000a: return struct{t01o;t03i}{f01(o01),o03}
	case 0x000b: return struct{t00i;t01o;t03i}{o00,f01(o01),o03}
	case 0x000c: return struct{t02o;t03i}{f02(o02),o03}
	case 0x000d: return struct{t00i;t02o;t03i}{o00,f02(o02),o03}
	case 0x000e: return struct{t01o;t02o;t03i}{f01(o01),f02(o02),o03}
	case 0x000f: return struct{t00i;t01o;t02o;t03i}{o00,f01(o01),f02(o02),o03}
	case 0x0010: return struct{t04i}{o04}
	case 0x0011: return struct{t00i;t04i}{o00,o04}
	case 0x0012: return struct{t01o;t04i}{f01(o01),o04}
	case 0x0013: return struct{t00i;t01o;t04i}{o00,f01(o01),o04}
	case 0x0014: return struct{t02o;t04i}{f02(o02),o04}
	case 0x0015: return struct{t00i;t02o;t04i}{o00,f02(o02),o04}
	case 0x0016: return struct{t01o;t02o;t04i}{f01(o01),f02(o02),o04}
	case 0x0017: return struct{t00i;t01o;t02o;t04i}{o00,f01(o01),f02(o02),o04}
	case 0x0018: return struct{t03i;t04i}{o03,o04}
	case 0x0019: return struct{t00i;t03i;t04i}{o00,o03,o04}
	case 0x001a: return struct{t01o;t03i;t04i}{f01(o01),o03,o04}
	case 0x001b: return struct{t00i;t01o;t03i;t04i}{o00,f01(o01),o03,o04}
	case 0x001c: return struct{t02o;t03i;t04i}{f02(o02),o03,o04}
	case 0x001d: return struct{t00i;t02o;t03i;t04i}{o00,f02(o02),o03,o04}
	case 0x001e: return struct{t01o;t02o;t03i;t04i}{f01(o01),f02(o02),o03,o04}
	case 0x001f: return struct{t00i;t01o;t02o;t03i;t04i}{o00,f01(o01),f02(o02),o03,o04}
	case 0x0020: return struct{t05o}{f05(o05)}
	case 0x0021: return struct{t00i;t05o}{o00,f05(o05)}
	case 0x0022: return struct{t01o;t05o}{f01(o01),f05(o05)}
	case 0x0023: return struct{t00i;t01o;t05o}{o00,f01(o01),f05(o05)}
	case 0x0024: return struct{t02o;t05o}{f02(o02),f05(o05)}
	case 0x0025: return struct{t00i;t02o;t05o}{o00,f02(o02),f05(o05)}
	case 0x0026: return struct{t01o;t02o;t05o}{f01(o01),f02(o02),f05(o05)}
	case 0x0027: return struct{t00i;t01o;t02o;t05o}{o00,f01(o01),f02(o02),f05(o05)}
	case 0x0028: return struct{t03i;t05o}{o03,f05(o05)}
	case 0x0029: return struct{t00i;t03i;t05o}{o00,o03,f05(o05)}
	case 0x002a: return struct{t01o;t03i;t05o}{f01(o01),o03,f05(o05)}
	case 0x002b: return struct{t00i;t01o;t03i;t05o}{o00,f01(o01),o03,f05(o05)}
	case 0x002c: return struct{t02o;t03i;t05o}{f02(o02),o03,f05(o05)}
	case 0x002d: return struct{t00i;t02o;t03i;t05o}{o00,f02(o02),o03,f05(o05)}
	case 0x002e: return struct{t01o;t02o;t03i;t05o}{f01(o01),f02(o02),o03,f05(o05)}
	case 0x002f: return struct{t00i;t01o;t02o;t03i;t05o}{o00,f01(o01),f02(o02),o03,f05(o05)}
	case 0x0030: return struct{t04i;t05o}{o04,f05(o05)}
	case 0x0031: return struct{t00i;t04i;t05o}{o00,o04,f05(o05)}
	case 0x0032: return struct{t01o;t04i;t05o}{f01(o01),o04,f05(o05)}
	case 0x0033: return struct{t00i;t01o;t04i;t05o}{o00,f01(o01),o04,f05(o05)}
	case 0x0034: return struct{t02o;t04i;t05o}{f02(o02),o04,f05(o05)}
	case 0x0035: return struct{t00i;t02o;t04i;t05o}{o00,f02(o02),o04,f05(o05)}
	case 0x0036: return struct{t01o;t02o;t04i;t05o}{f01(o01),f02(o02),o04,f05(o05)}
	case 0x0037: return struct{t00i;t01o;t02o;t04i;t05o}{o00,f01(o01),f02(o02),o04,f05(o05)}
	case 0x0038: return struct{t03i;t04i;t05o}{o03,o04,f05(o05)}
	case 0x0039: return struct{t00i;t03i;t04i;t05o}{o00,o03,o04,f05(o05)}
	case 0x003a: return struct{t01o;t03i;t04i;t05o}{f01(o01),o03,o04,f05(o05)}
	case 0x003b: return struct{t00i;t01o;t03i;t04i;t05o}{o00,f01(o01),o03,o04,f05(o05)}
	case 0x003c: return struct{t02o;t03i;t04i;t05o}{f02(o02),o03,o04,f05(o05)}
	case 0x003d: return struct{t00i;t02o;t03i;t04i;t05o}{o00,f02(o02),o03,o04,f05(o05)}
	case 0x003e: return struct{t01o;t02o;t03i;t04i;t05o}{f01(o01),f02(o02),o03,o04,f05(o05)}
	case 0x003f: return struct{t00i;t01o;t02o;t03i;t04i;t05o}{o00,f01(o01),f02(o02),o03,o04,f05(o05)}
	case 0x0040: return struct{t06o}{f06(o06)}
	case 0x0041: return struct{t00i;t06o}{o00,f06(o06)}
	case 0x0042: return struct{t01o;t06o}{f01(o01),f06(o06)}
	case 0x0043: return struct{t00i;t01o;t06o}{o00,f01(o01),f06(o06)}
	case 0x0044: return struct{t02o;t06o}{f02(o02),f06(o06)}
	case 0x0045: return struct{t00i;t02o;t06o}{o00,f02(o02),f06(o06)}
	case 0x0046: return struct{t01o;t02o;t06o}{f01(o01),f02(o02),f06(o06)}
	case 0x0047: return struct{t00i;t01o;t02o;t06o}{o00,f01(o01),f02(o02),f06(o06)}
	case 0x0048: return struct{t03i;t06o}{o03,f06(o06)}
	case 0x0049: return struct{t00i;t03i;t06o}{o00,o03,f06(o06)}
	case 0x004a: return struct{t01o;t03i;t06o}{f01(o01),o03,f06(o06)}
	case 0x004b: return struct{t00i;t01o;t03i;t06o}{o00,f01(o01),o03,f06(o06)}
	case 0x004c: return struct{t02o;t03i;t06o}{f02(o02),o03,f06(o06)}
	case 0x004d: return struct{t00i;t02o;t03i;t06o}{o00,f02(o02),o03,f06(o06)}
	case 0x004e: return struct{t01o;t02o;t03i;t06o}{f01(o01),f02(o02),o03,f06(o06)}
	case 0x004f: return struct{t00i;t01o;t02o;t03i;t06o}{o00,f01(o01),f02(o02),o03,f06(o06)}
	case 0x0050: return struct{t04i;t06o}{o04,f06(o06)}
	case 0x0051: return struct{t00i;t04i;t06o}{o00,o04,f06(o06)}
	case 0x0052: return struct{t01o;t04i;t06o}{f01(o01),o04,f06(o06)}
	case 0x0053: return struct{t00i;t01o;t04i;t06o}{o00,f01(o01),o04,f06(o06)}
	case 0x0054: return struct{t02o;t04i;t06o}{f02(o02),o04,f06(o06)}
	case 0x0055: return struct{t00i;t02o;t04i;t06o}{o00,f02(o02),o04,f06(o06)}
	case 0x0056: return struct{t01o;t02o;t04i;t06o}{f01(o01),f02(o02),o04,f06(o06)}
	case 0x0057: return struct{t00i;t01o;t02o;t04i;t06o}{o00,f01(o01),f02(o02),o04,f06(o06)}
	case 0x0058: return struct{t03i;t04i;t06o}{o03,o04,f06(o06)}
	case 0x0059: return struct{t00i;t03i;t04i;t06o}{o00,o03,o04,f06(o06)}
	case 0x005a: return struct{t01o;t03i;t04i;t06o}{f01(o01),o03,o04,f06(o06)}
	case 0x005b: return struct{t00i;t01o;t03i;t04i;t06o}{o00,f01(o01),o03,o04,f06(o06)}
	case 0x005c: return struct{t02o;t03i;t04i;t06o}{f02(o02),o03,o04,f06(o06)}
	case 0x005d: return struct{t00i;t02o;t03i;t04i;t06o}{o00,f02(o02),o03,o04,f06(o06)}
	case 0x005e: return struct{t01o;t02o;t03i;t04i;t06o}{f01(o01),f02(o02),o03,o04,f06(o06)}
	case 0x005f: return struct{t00i;t01o;t02o;t03i;t04i;t06o}{o00,f01(o01),f02(o02),o03,o04,f06(o06)}
	case 0x0060: return struct{t05o;t06o}{f05(o05),f06(o06)}
	case 0x0061: return struct{t00i;t05o;t06o}{o00,f05(o05),f06(o06)}
	case 0x0062: return struct{t01o;t05o;t06o}{f01(o01),f05(o05),f06(o06)}
	case 0x0063: return struct{t00i;t01o;t05o;t06o}{o00,f01(o01),f05(o05),f06(o06)}
	case 0x0064: return struct{t02o;t05o;t06o}{f02(o02),f05(o05),f06(o06)}
	case 0x0065: return struct{t00i;t02o;t05o;t06o}{o00,f02(o02),f05(o05),f06(o06)}
	case 0x0066: return struct{t01o;t02o;t05o;t06o}{f01(o01),f02(o02),f05(o05),f06(o06)}
	case 0x0067: return struct{t00i;t01o;t02o;t05o;t06o}{o00,f01(o01),f02(o02),f05(o05),f06(o06)}
	case 0x0068: return struct{t03i;t05o;t06o}{o03,f05(o05),f06(o06)}
	case 0x0069: return struct{t00i;t03i;t05o;t06o}{o00,o03,f05(o05),f06(o06)}
	case 0x006a: return struct{t01o;t03i;t05o;t06o}{f01(o01),o03,f05(o05),f06(o06)}
	case 0x006b: return struct{t00i;t01o;t03i;t05o;t06o}{o00,f01(o01),o03,f05(o05),f06(o06)}
	case 0x006c: return struct{t02o;t03i;t05o;t06o}{f02(o02),o03,f05(o05),f06(o06)}
	case 0x006d: return struct{t00i;t02o;t03i;t05o;t06o}{o00,f02(o02),o03,f05(o05),f06(o06)}
	case 0x006e: return struct{t01o;t02o;t03i;t05o;t06o}{f01(o01),f02(o02),o03,f05(o05),f06(o06)}
	case 0x006f: return struct{t00i;t01o;t02o;t03i;t05o;t06o}{o00,f01(o01),f02(o02),o03,f05(o05),f06(o06)}
	case 0x0070: return struct{t04i;t05o;t06o}{o04,f05(o05),f06(o06)}
	case 0x0071: return struct{t00i;t04i;t05o;t06o}{o00,o04,f05(o05),f06(o06)}
	case 0x0072: return struct{t01o;t04i;t05o;t06o}{f01(o01),o04,f05(o05),f06(o06)}
	case 0x0073: return struct{t00i;t01o;t04i;t05o;t06o}{o00,f01(o01),o04,f05(o05),f06(o06)}
	case 0x0074: return struct{t02o;t04i;t05o;t06o}{f02(o02),o04,f05(o05),f06(o06)}
	case 0x0075: return struct{t00i;t02o;t04i;t05o;t06o}{o00,f02(o02),o04,f05(o05),f06(o06)}
	case 0x0076: return struct{t01o;t02o;t04i;t05o;t06o}{f01(o01),f02(o02),o04,f05(o05),f06(o06)}
	case 0x0077: return struct{t00i;t01o;t02o;t04i;t05o;t06o}{o00,f01(o01),f02(o02),o04,f05(o05),f06(o06)}
	case 0x0078: return struct{t03i;t04i;t05o;t06o}{o03,o04,f05(o05),f06(o06)}
	case 0x0079: return struct{t00i;t03i;t04i;t05o;t06o}{o00,o03,o04,f05(o05),f06(o06)}
	case 0x007a: return struct{t01o;t03i;t04i;t05o;t06o}{f01(o01),o03,o04,f05(o05),f06(o06)}
	case 0x007b: return struct{t00i;t01o;t03i;t04i;t05o;t06o}{o00,f01(o01),o03,o04,f05(o05),f06(o06)}
	case 0x007c: return struct{t02o;t03i;t04i;t05o;t06o}{f02(o02),o03,o04,f05(o05),f06(o06)}
	case 0x007d: return struct{t00i;t02o;t03i;t04i;t05o;t06o}{o00,f02(o02),o03,o04,f05(o05),f06(o06)}
	case 0x007e: return struct{t01o;t02o;t03i;t04i;t05o;t06o}{f01(o01),f02(o02),o03,o04,f05(o05),f06(o06)}
	case 0x007f: return struct{t00i;t01o;t02o;t03i;t04i;t05o;t06o}{o00,f01(o01),f02(o02),o03,o04,f05(o05),f06(o06)}
	case 0x0080: return struct{t07i}{o07}
	case 0x0081: return struct{t00i;t07i}{o00,o07}
	case 0x0082: return struct{t01o;t07i}{f01(o01),o07}
	case 0x0083: return struct{t00i;t01o;t07i}{o00,f01(o01),o07}
	case 0x0084: return struct{t02o;t07i}{f02(o02),o07}
	case 0x0085: return struct{t00i;t02o;t07i}{o00,f02(o02),o07}
	case 0x0086: return struct{t01o;t02o;t07i}{f01(o01),f02(o02),o07}
	case 0x0087: return struct{t00i;t01o;t02o;t07i}{o00,f01(o01),f02(o02),o07}
	case 0x0088: return struct{t03i;t07i}{o03,o07}
	case 0x0089: return struct{t00i;t03i;t07i}{o00,o03,o07}
	case 0x008a: return struct{t01o;t03i;t07i}{f01(o01),o03,o07}
	case 0x008b: return struct{t00i;t01o;t03i;t07i}{o00,f01(o01),o03,o07}
	case 0x008c: return struct{t02o;t03i;t07i}{f02(o02),o03,o07}
	case 0x008d: return struct{t00i;t02o;t03i;t07i}{o00,f02(o02),o03,o07}
	case 0x008e: return struct{t01o;t02o;t03i;t07i}{f01(o01),f02(o02),o03,o07}
	case 0x008f: return struct{t00i;t01o;t02o;t03i;t07i}{o00,f01(o01),f02(o02),o03,o07}
	case 0x0090: return struct{t04i;t07i}{o04,o07}
	case 0x0091: return struct{t00i;t04i;t07i}{o00,o04,o07}
	case 0x0092: return struct{t01o;t04i;t07i}{f01(o01),o04,o07}
	case 0x0093: return struct{t00i;t01o;t04i;t07i}{o00,f01(o01),o04,o07}
	case 0x0094: return struct{t02o;t04i;t07i}{f02(o02),o04,o07}
	case 0x0095: return struct{t00i;t02o;t04i;t07i}{o00,f02(o02),o04,o07}
	case 0x0096: return struct{t01o;t02o;t04i;t07i}{f01(o01),f02(o02),o04,o07}
	case 0x0097: return struct{t00i;t01o;t02o;t04i;t07i}{o00,f01(o01),f02(o02),o04,o07}
	case 0x0098: return struct{t03i;t04i;t07i}{o03,o04,o07}
	case 0x0099: return struct{t00i;t03i;t04i;t07i}{o00,o03,o04,o07}
	case 0x009a: return struct{t01o;t03i;t04i;t07i}{f01(o01),o03,o04,o07}
	case 0x009b: return struct{t00i;t01o;t03i;t04i;t07i}{o00,f01(o01),o03,o04,o07}
	case 0x009c: return struct{t02o;t03i;t04i;t07i}{f02(o02),o03,o04,o07}
	case 0x009d: return struct{t00i;t02o;t03i;t04i;t07i}{o00,f02(o02),o03,o04,o07}
	case 0x009e: return struct{t01o;t02o;t03i;t04i;t07i}{f01(o01),f02(o02),o03,o04,o07}
	case 0x009f: return struct{t00i;t01o;t02o;t03i;t04i;t07i}{o00,f01(o01),f02(o02),o03,o04,o07}
	case 0x00a0: return struct{t05o;t07i}{f05(o05),o07}
	case 0x00a1: return struct{t00i;t05o;t07i}{o00,f05(o05),o07}
	case 0x00a2: return struct{t01o;t05o;t07i}{f01(o01),f05(o05),o07}
	case 0x00a3: return struct{t00i;t01o;t05o;t07i}{o00,f01(o01),f05(o05),o07}
	case 0x00a4: return struct{t02o;t05o;t07i}{f02(o02),f05(o05),o07}
	case 0x00a5: return struct{t00i;t02o;t05o;t07i}{o00,f02(o02),f05(o05),o07}
	case 0x00a6: return struct{t01o;t02o;t05o;t07i}{f01(o01),f02(o02),f05(o05),o07}
	case 0x00a7: return struct{t00i;t01o;t02o;t05o;t07i}{o00,f01(o01),f02(o02),f05(o05),o07}
	case 0x00a8: return struct{t03i;t05o;t07i}{o03,f05(o05),o07}
	case 0x00a9: return struct{t00i;t03i;t05o;t07i}{o00,o03,f05(o05),o07}
	case 0x00aa: return struct{t01o;t03i;t05o;t07i}{f01(o01),o03,f05(o05),o07}
	case 0x00ab: return struct{t00i;t01o;t03i;t05o;t07i}{o00,f01(o01),o03,f05(o05),o07}
	case 0x00ac: return struct{t02o;t03i;t05o;t07i}{f02(o02),o03,f05(o05),o07}
	case 0x00ad: return struct{t00i;t02o;t03i;t05o;t07i}{o00,f02(o02),o03,f05(o05),o07}
	case 0x00ae: return struct{t01o;t02o;t03i;t05o;t07i}{f01(o01),f02(o02),o03,f05(o05),o07}
	case 0x00af: return struct{t00i;t01o;t02o;t03i;t05o;t07i}{o00,f01(o01),f02(o02),o03,f05(o05),o07}
	case 0x00b0: return struct{t04i;t05o;t07i}{o04,f05(o05),o07}
	case 0x00b1: return struct{t00i;t04i;t05o;t07i}{o00,o04,f05(o05),o07}
	case 0x00b2: return struct{t01o;t04i;t05o;t07i}{f01(o01),o04,f05(o05),o07}
	case 0x00b3: return struct{t00i;t01o;t04i;t05o;t07i}{o00,f01(o01),o04,f05(o05),o07}
	case 0x00b4: return struct{t02o;t04i;t05o;t07i}{f02(o02),o04,f05(o05),o07}
	case 0x00b5: return struct{t00i;t02o;t04i;t05o;t07i}{o00,f02(o02),o04,f05(o05),o07}
	case 0x00b6: return struct{t01o;t02o;t04i;t05o;t07i}{f01(o01),f02(o02),o04,f05(o05),o07}
	case 0x00b7: return struct{t00i;t01o;t02o;t04i;t05o;t07i}{o00,f01(o01),f02(o02),o04,f05(o05),o07}
	case 0x00b8: return struct{t03i;t04i;t05o;t07i}{o03,o04,f05(o05),o07}
	case 0x00b9: return struct{t00i;t03i;t04i;t05o;t07i}{o00,o03,o04,f05(o05),o07}
	case 0x00ba: return struct{t01o;t03i;t04i;t05o;t07i}{f01(o01),o03,o04,f05(o05),o07}
	case 0x00bb: return struct{t00i;t01o;t03i;t04i;t05o;t07i}{o00,f01(o01),o03,o04,f05(o05),o07}
	case 0x00bc: return struct{t02o;t03i;t04i;t05o;t07i}{f02(o02),o03,o04,f05(o05),o07}
	case 0x00bd: return struct{t00i;t02o;t03i;t04i;t05o;t07i}{o00,f02(o02),o03,o04,f05(o05),o07}
	case 0x00be: return struct{t01o;t02o;t03i;t04i;t05o;t07i}{f01(o01),f02(o02),o03,o04,f05(o05),o07}
	case 0x00bf: return struct{t00i;t01o;t02o;t03i;t04i;t05o;t07i}{o00,f01(o01),f02(o02),o03,o04,f05(o05),o07}
	case 0x00c0: return struct{t06o;t07i}{f06(o06),o07}
	case 0x00c1: return struct{t00i;t06o;t07i}{o00,f06(o06),o07}
	case 0x00c2: return struct{t01o;t06o;t07i}{f01(o01),f06(o06),o07}
	case 0x00c3: return struct{t00i;t01o;t06o;t07i}{o00,f01(o01),f06(o06),o07}
	case 0x00c4: return struct{t02o;t06o;t07i}{f02(o02),f06(o06),o07}
	case 0x00c5: return struct{t00i;t02o;t06o;t07i}{o00,f02(o02),f06(o06),o07}
	case 0x00c6: return struct{t01o;t02o;t06o;t07i}{f01(o01),f02(o02),f06(o06),o07}
	case 0x00c7: return struct{t00i;t01o;t02o;t06o;t07i}{o00,f01(o01),f02(o02),f06(o06),o07}
	case 0x00c8: return struct{t03i;t06o;t07i}{o03,f06(o06),o07}
	case 0x00c9: return struct{t00i;t03i;t06o;t07i}{o00,o03,f06(o06),o07}
	case 0x00ca: return struct{t01o;t03i;t06o;t07i}{f01(o01),o03,f06(o06),o07}
	case 0x00cb: return struct{t00i;t01o;t03i;t06o;t07i}{o00,f01(o01),o03,f06(o06),o07}
	case 0x00cc: return struct{t02o;t03i;t06o;t07i}{f02(o02),o03,f06(o06),o07}
	case 0x00cd: return struct{t00i;t02o;t03i;t06o;t07i}{o00,f02(o02),o03,f06(o06),o07}
	case 0x00ce: return struct{t01o;t02o;t03i;t06o;t07i}{f01(o01),f02(o02),o03,f06(o06),o07}
	case 0x00cf: return struct{t00i;t01o;t02o;t03i;t06o;t07i}{o00,f01(o01),f02(o02),o03,f06(o06),o07}
	case 0x00d0: return struct{t04i;t06o;t07i}{o04,f06(o06),o07}
	case 0x00d1: return struct{t00i;t04i;t06o;t07i}{o00,o04,f06(o06),o07}
	case 0x00d2: return struct{t01o;t04i;t06o;t07i}{f01(o01),o04,f06(o06),o07}
	case 0x00d3: return struct{t00i;t01o;t04i;t06o;t07i}{o00,f01(o01),o04,f06(o06),o07}
	case 0x00d4: return struct{t02o;t04i;t06o;t07i}{f02(o02),o04,f06(o06),o07}
	case 0x00d5: return struct{t00i;t02o;t04i;t06o;t07i}{o00,f02(o02),o04,f06(o06),o07}
	case 0x00d6: return struct{t01o;t02o;t04i;t06o;t07i}{f01(o01),f02(o02),o04,f06(o06),o07}
	case 0x00d7: return struct{t00i;t01o;t02o;t04i;t06o;t07i}{o00,f01(o01),f02(o02),o04,f06(o06),o07}
	case 0x00d8: return struct{t03i;t04i;t06o;t07i}{o03,o04,f06(o06),o07}
	case 0x00d9: return struct{t00i;t03i;t04i;t06o;t07i}{o00,o03,o04,f06(o06),o07}
	case 0x00da: return struct{t01o;t03i;t04i;t06o;t07i}{f01(o01),o03,o04,f06(o06),o07}
	case 0x00db: return struct{t00i;t01o;t03i;t04i;t06o;t07i}{o00,f01(o01),o03,o04,f06(o06),o07}
	case 0x00dc: return struct{t02o;t03i;t04i;t06o;t07i}{f02(o02),o03,o04,f06(o06),o07}
	case 0x00dd: return struct{t00i;t02o;t03i;t04i;t06o;t07i}{o00,f02(o02),o03,o04,f06(o06),o07}
	case 0x00de: return struct{t01o;t02o;t03i;t04i;t06o;t07i}{f01(o01),f02(o02),o03,o04,f06(o06),o07}
	case 0x00df: return struct{t00i;t01o;t02o;t03i;t04i;t06o;t07i}{o00,f01(o01),f02(o02),o03,o04,f06(o06),o07}
	case 0x00e0: return struct{t05o;t06o;t07i}{f05(o05),f06(o06),o07}
	case 0x00e1: return struct{t00i;t05o;t06o;t07i}{o00,f05(o05),f06(o06),o07}
	case 0x00e2: return struct{t01o;t05o;t06o;t07i}{f01(o01),f05(o05),f06(o06),o07}
	case 0x00e3: return struct{t00i;t01o;t05o;t06o;t07i}{o00,f01(o01),f05(o05),f06(o06),o07}
	case 0x00e4: return struct{t02o;t05o;t06o;t07i}{f02(o02),f05(o05),f06(o06),o07}
	case 0x00e5: return struct{t00i;t02o;t05o;t06o;t07i}{o00,f02(o02),f05(o05),f06(o06),o07}
	case 0x00e6: return struct{t01o;t02o;t05o;t06o;t07i}{f01(o01),f02(o02),f05(o05),f06(o06),o07}
	case 0x00e7: return struct{t00i;t01o;t02o;t05o;t06o;t07i}{o00,f01(o01),f02(o02),f05(o05),f06(o06),o07}
	case 0x00e8: return struct{t03i;t05o;t06o;t07i}{o03,f05(o05),f06(o06),o07}
	case 0x00e9: return struct{t00i;t03i;t05o;t06o;t07i}{o00,o03,f05(o05),f06(o06),o07}
	case 0x00ea: return struct{t01o;t03i;t05o;t06o;t07i}{f01(o01),o03,f05(o05),f06(o06),o07}
	case 0x00eb: return struct{t00i;t01o;t03i;t05o;t06o;t07i}{o00,f01(o01),o03,f05(o05),f06(o06),o07}
	case 0x00ec: return struct{t02o;t03i;t05o;t06o;t07i}{f02(o02),o03,f05(o05),f06(o06),o07}
	case 0x00ed: return struct{t00i;t02o;t03i;t05o;t06o;t07i}{o00,f02(o02),o03,f05(o05),f06(o06),o07}
	case 0x00ee: return struct{t01o;t02o;t03i;t05o;t06o;t07i}{f01(o01),f02(o02),o03,f05(o05),f06(o06),o07}
	case 0x00ef: return struct{t00i;t01o;t02o;t03i;t05o;t06o;t07i}{o00,f01(o01),f02(o02),o03,f05(o05),f06(o06),o07}
	case 0x00f0: return struct{t04i;t05o;t06o;t07i}{o04,f05(o05),f06(o06),o07}
	case 0x00f1: return struct{t00i;t04i;t05o;t06o;t07i}{o00,o04,f05(o05),f06(o06),o07}
	case 0x00f2: return struct{t01o;t04i;t05o;t06o;t07i}{f01(o01),o04,f05(o05),f06(o06),o07}
	case 0x00f3: return struct{t00i;t01o;t04i;t05o;t06o;t07i}{o00,f01(o01),o04,f05(o05),f06(o06),o07}
	case 0x00f4: return struct{t02o;t04i;t05o;t06o;t07i}{f02(o02),o04,f05(o05),f06(o06),o07}
	case 0x00f5: return struct{t00i;t02o;t04i;t05o;t06o;t07i}{o00,f02(o02),o04,f05(o05),f06(o06),o07}
	case 0x00f6: return struct{t01o;t02o;t04i;t05o;t06o;t07i}{f01(o01),f02(o02),o04,f05(o05),f06(o06),o07}
	case 0x00f7: return struct{t00i;t01o;t02o;t04i;t05o;t06o;t07i}{o00,f01(o01),f02(o02),o04,f05(o05),f06(o06),o07}
	case 0x00f8: return struct{t03i;t04i;t05o;t06o;t07i}{o03,o04,f05(o05),f06(o06),o07}
	case 0x00f9: return struct{t00i;t03i;t04i;t05o;t06o;t07i}{o00,o03,o04,f05(o05),f06(o06),o07}
	case 0x00fa: return struct{t01o;t03i;t04i;t05o;t06o;t07i}{f01(o01),o03,o04,f05(o05),f06(o06),o07}
	case 0x00fb: return struct{t00i;t01o;t03i;t04i;t05o;t06o;t07i}{o00,f01(o01),o03,o04,f05(o05),f06(o06),o07}
	case 0x00fc: return struct{t02o;t03i;t04i;t05o;t06o;t07i}{f02(o02),o03,o04,f05(o05),f06(o06),o07}
	case 0x00fd: return struct{t00i;t02o;t03i;t04i;t05o;t06o;t07i}{o00,f02(o02),o03,o04,f05(o05),f06(o06),o07}
	case 0x00fe: return struct{t01o;t02o;t03i;t04i;t05o;t06o;t07i}{f01(o01),f02(o02),o03,o04,f05(o05),f06(o06),o07}
	case 0x00ff: return struct{t00i;t01o;t02o;t03i;t04i;t05o;t06o;t07i}{o00,f01(o01),f02(o02),o03,o04,f05(o05),f06(o06),o07}
	}

	panic("unreachable")
}
